const BUILD_INFO = {
  "version": "v2.3.0",
  "name": "Mobile Fullscreen UX",
  "date": "30/05/2026",
  "time": "23h59",
  "label": "Build v2.3.0 — 30/05/2026 — 23h59"
};

const SECTIONS = [
  {
    "id": "brasil-1958",
    "title": "Brasil 1958",
    "subtitle": "Primeira estrela mundial",
    "type": "campea",
    "group": "Brasil Pentacampeão",
    "color": "#0a7d49"
  },
  {
    "id": "brasil-1962",
    "title": "Brasil 1962",
    "subtitle": "O bicampeonato do Brasil",
    "type": "campea",
    "group": "Brasil Pentacampeão",
    "color": "#0b8a4e"
  },
  {
    "id": "brasil-1970",
    "title": "Brasil 1970",
    "subtitle": "A seleção eterna",
    "type": "campea",
    "group": "Brasil Pentacampeão",
    "color": "#dfb13c"
  },
  {
    "id": "brasil-1994",
    "title": "Brasil 1994",
    "subtitle": "O tetra nos Estados Unidos",
    "type": "campea",
    "group": "Brasil Pentacampeão",
    "color": "#174aa3"
  },
  {
    "id": "brasil-2002",
    "title": "Brasil 2002",
    "subtitle": "O penta histórico",
    "type": "campea",
    "group": "Brasil Pentacampeão",
    "color": "#059660"
  },
  {
    "id": "brasil-2026",
    "title": "Brasil 2026",
    "subtitle": "Seleção atual — edição especial",
    "type": "atual",
    "group": "Copa 2026",
    "color": "#e8c244"
  },
  {
    "id": "sel-argentina",
    "title": "Argentina",
    "subtitle": "Seleção 2026 — CONMEBOL",
    "type": "selecoes-2026",
    "group": "Copa 2026",
    "color": "#0b5ba8"
  },
  {
    "id": "sel-franca",
    "title": "França",
    "subtitle": "Seleção 2026 — UEFA",
    "type": "selecoes-2026",
    "group": "Copa 2026",
    "color": "#0b5ba8"
  },
  {
    "id": "sel-portugal",
    "title": "Portugal",
    "subtitle": "Seleção 2026 — UEFA",
    "type": "selecoes-2026",
    "group": "Copa 2026",
    "color": "#0b5ba8"
  },
  {
    "id": "sel-inglaterra",
    "title": "Inglaterra",
    "subtitle": "Seleção 2026 — UEFA",
    "type": "selecoes-2026",
    "group": "Copa 2026",
    "color": "#0b5ba8"
  },
  {
    "id": "sel-espanha",
    "title": "Espanha",
    "subtitle": "Seleção 2026 — UEFA",
    "type": "selecoes-2026",
    "group": "Copa 2026",
    "color": "#0b5ba8"
  },
  {
    "id": "sel-alemanha",
    "title": "Alemanha",
    "subtitle": "Seleção 2026 — UEFA",
    "type": "selecoes-2026",
    "group": "Copa 2026",
    "color": "#0b5ba8"
  },
  {
    "id": "sel-italia",
    "title": "Itália",
    "subtitle": "Seleção 2026 — UEFA",
    "type": "selecoes-2026",
    "group": "Copa 2026",
    "color": "#0b5ba8"
  },
  {
    "id": "sel-holanda",
    "title": "Holanda",
    "subtitle": "Seleção 2026 — UEFA",
    "type": "selecoes-2026",
    "group": "Copa 2026",
    "color": "#0b5ba8"
  },
  {
    "id": "sel-uruguai",
    "title": "Uruguai",
    "subtitle": "Seleção 2026 — CONMEBOL",
    "type": "selecoes-2026",
    "group": "Copa 2026",
    "color": "#0b5ba8"
  },
  {
    "id": "sel-colombia",
    "title": "Colômbia",
    "subtitle": "Seleção 2026 — CONMEBOL",
    "type": "selecoes-2026",
    "group": "Copa 2026",
    "color": "#0b5ba8"
  },
  {
    "id": "sel-mexico",
    "title": "México",
    "subtitle": "Seleção 2026 — CONCACAF",
    "type": "selecoes-2026",
    "group": "Copa 2026",
    "color": "#0b5ba8"
  },
  {
    "id": "sel-estados-unidos",
    "title": "Estados Unidos",
    "subtitle": "Seleção 2026 — CONCACAF",
    "type": "selecoes-2026",
    "group": "Copa 2026",
    "color": "#0b5ba8"
  },
  {
    "id": "sel-canada",
    "title": "Canadá",
    "subtitle": "Seleção 2026 — CONCACAF",
    "type": "selecoes-2026",
    "group": "Copa 2026",
    "color": "#0b5ba8"
  },
  {
    "id": "sel-marrocos",
    "title": "Marrocos",
    "subtitle": "Seleção 2026 — CAF",
    "type": "selecoes-2026",
    "group": "Copa 2026",
    "color": "#0b5ba8"
  },
  {
    "id": "sel-japao",
    "title": "Japão",
    "subtitle": "Seleção 2026 — AFC",
    "type": "selecoes-2026",
    "group": "Copa 2026",
    "color": "#0b5ba8"
  },
  {
    "id": "sel-coreia-do-sul",
    "title": "Coreia do Sul",
    "subtitle": "Seleção 2026 — AFC",
    "type": "selecoes-2026",
    "group": "Copa 2026",
    "color": "#0b5ba8"
  },
  {
    "id": "especiais",
    "title": "Figurinhas Especiais",
    "subtitle": "Cards premium de demonstração e convidados",
    "type": "especial",
    "group": "Edição Especial",
    "color": "#9b6bff"
  }
];

const STICKERS = [
  {
    "id": "brasil-1958-pele-01",
    "name": "Pelé",
    "team": "Brasil 1958",
    "section": "brasil-1958",
    "number": "10",
    "position": "Atacante",
    "rarity": "lendaria",
    "image": "assets/images/stickers/brasil-1958/brasil-1958-pele-01.webp",
    "era": "Primeira estrela mundial"
  },
  {
    "id": "brasil-1958-garrincha-02",
    "name": "Garrincha",
    "team": "Brasil 1958",
    "section": "brasil-1958",
    "number": "7",
    "position": "Ponta",
    "rarity": "lendaria",
    "image": "assets/images/stickers/brasil-1958/brasil-1958-garrincha-02.webp",
    "era": "Primeira estrela mundial"
  },
  {
    "id": "brasil-1958-didi-03",
    "name": "Didi",
    "team": "Brasil 1958",
    "section": "brasil-1958",
    "number": "8",
    "position": "Meia",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-1958/brasil-1958-didi-03.webp",
    "era": "Primeira estrela mundial"
  },
  {
    "id": "brasil-1958-vava-04",
    "name": "Vavá",
    "team": "Brasil 1958",
    "section": "brasil-1958",
    "number": "20",
    "position": "Atacante",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-1958/brasil-1958-vava-04.webp",
    "era": "Primeira estrela mundial"
  },
  {
    "id": "brasil-1958-nilton-santos-05",
    "name": "Nilton Santos",
    "team": "Brasil 1958",
    "section": "brasil-1958",
    "number": "6",
    "position": "Lateral",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-1958/brasil-1958-nilton-santos-05.webp",
    "era": "Primeira estrela mundial"
  },
  {
    "id": "brasil-1958-djalma-santos-06",
    "name": "Djalma Santos",
    "team": "Brasil 1958",
    "section": "brasil-1958",
    "number": "4",
    "position": "Lateral",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-1958/brasil-1958-djalma-santos-06.webp",
    "era": "Primeira estrela mundial"
  },
  {
    "id": "brasil-1958-bellini-07",
    "name": "Bellini",
    "team": "Brasil 1958",
    "section": "brasil-1958",
    "number": "3",
    "position": "Zagueiro",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-1958/brasil-1958-bellini-07.webp",
    "era": "Primeira estrela mundial"
  },
  {
    "id": "brasil-1958-gilmar-08",
    "name": "Gilmar",
    "team": "Brasil 1958",
    "section": "brasil-1958",
    "number": "1",
    "position": "Goleiro",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-1958/brasil-1958-gilmar-08.webp",
    "era": "Primeira estrela mundial"
  },
  {
    "id": "brasil-1958-zagallo-09",
    "name": "Zagallo",
    "team": "Brasil 1958",
    "section": "brasil-1958",
    "number": "11",
    "position": "Ponta",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-1958/brasil-1958-zagallo-09.webp",
    "era": "Primeira estrela mundial"
  },
  {
    "id": "brasil-1958-orlando-10",
    "name": "Orlando",
    "team": "Brasil 1958",
    "section": "brasil-1958",
    "number": "2",
    "position": "Zagueiro",
    "rarity": "comum",
    "image": "assets/images/stickers/brasil-1958/brasil-1958-orlando-10.webp",
    "era": "Primeira estrela mundial"
  },
  {
    "id": "brasil-1958-zito-11",
    "name": "Zito",
    "team": "Brasil 1958",
    "section": "brasil-1958",
    "number": "5",
    "position": "Volante",
    "rarity": "comum",
    "image": "assets/images/stickers/brasil-1958/brasil-1958-zito-11.webp",
    "era": "Primeira estrela mundial"
  },
  {
    "id": "brasil-1958-mazzola-12",
    "name": "Mazzola",
    "team": "Brasil 1958",
    "section": "brasil-1958",
    "number": "18",
    "position": "Atacante",
    "rarity": "comum",
    "image": "assets/images/stickers/brasil-1958/brasil-1958-mazzola-12.webp",
    "era": "Primeira estrela mundial"
  },
  {
    "id": "brasil-1962-garrincha-01",
    "name": "Garrincha",
    "team": "Brasil 1962",
    "section": "brasil-1962",
    "number": "7",
    "position": "Ponta",
    "rarity": "lendaria",
    "image": "assets/images/stickers/brasil-1962/brasil-1962-garrincha-01.webp",
    "era": "O bicampeonato do Brasil"
  },
  {
    "id": "brasil-1962-pele-02",
    "name": "Pelé",
    "team": "Brasil 1962",
    "section": "brasil-1962",
    "number": "10",
    "position": "Atacante",
    "rarity": "lendaria",
    "image": "assets/images/stickers/brasil-1962/brasil-1962-pele-02.webp",
    "era": "O bicampeonato do Brasil"
  },
  {
    "id": "brasil-1962-amarildo-03",
    "name": "Amarildo",
    "team": "Brasil 1962",
    "section": "brasil-1962",
    "number": "20",
    "position": "Atacante",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-1962/brasil-1962-amarildo-03.webp",
    "era": "O bicampeonato do Brasil"
  },
  {
    "id": "brasil-1962-vava-04",
    "name": "Vavá",
    "team": "Brasil 1962",
    "section": "brasil-1962",
    "number": "9",
    "position": "Atacante",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-1962/brasil-1962-vava-04.webp",
    "era": "O bicampeonato do Brasil"
  },
  {
    "id": "brasil-1962-didi-05",
    "name": "Didi",
    "team": "Brasil 1962",
    "section": "brasil-1962",
    "number": "8",
    "position": "Meia",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-1962/brasil-1962-didi-05.webp",
    "era": "O bicampeonato do Brasil"
  },
  {
    "id": "brasil-1962-zagallo-06",
    "name": "Zagallo",
    "team": "Brasil 1962",
    "section": "brasil-1962",
    "number": "11",
    "position": "Ponta",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-1962/brasil-1962-zagallo-06.webp",
    "era": "O bicampeonato do Brasil"
  },
  {
    "id": "brasil-1962-zito-07",
    "name": "Zito",
    "team": "Brasil 1962",
    "section": "brasil-1962",
    "number": "5",
    "position": "Volante",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-1962/brasil-1962-zito-07.webp",
    "era": "O bicampeonato do Brasil"
  },
  {
    "id": "brasil-1962-nilton-santos-08",
    "name": "Nilton Santos",
    "team": "Brasil 1962",
    "section": "brasil-1962",
    "number": "6",
    "position": "Lateral",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-1962/brasil-1962-nilton-santos-08.webp",
    "era": "O bicampeonato do Brasil"
  },
  {
    "id": "brasil-1962-djalma-santos-09",
    "name": "Djalma Santos",
    "team": "Brasil 1962",
    "section": "brasil-1962",
    "number": "4",
    "position": "Lateral",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-1962/brasil-1962-djalma-santos-09.webp",
    "era": "O bicampeonato do Brasil"
  },
  {
    "id": "brasil-1962-mauro-ramos-10",
    "name": "Mauro Ramos",
    "team": "Brasil 1962",
    "section": "brasil-1962",
    "number": "3",
    "position": "Zagueiro",
    "rarity": "comum",
    "image": "assets/images/stickers/brasil-1962/brasil-1962-mauro-ramos-10.webp",
    "era": "O bicampeonato do Brasil"
  },
  {
    "id": "brasil-1962-gilmar-11",
    "name": "Gilmar",
    "team": "Brasil 1962",
    "section": "brasil-1962",
    "number": "1",
    "position": "Goleiro",
    "rarity": "comum",
    "image": "assets/images/stickers/brasil-1962/brasil-1962-gilmar-11.webp",
    "era": "O bicampeonato do Brasil"
  },
  {
    "id": "brasil-1962-zozimo-12",
    "name": "Zózimo",
    "team": "Brasil 1962",
    "section": "brasil-1962",
    "number": "2",
    "position": "Zagueiro",
    "rarity": "comum",
    "image": "assets/images/stickers/brasil-1962/brasil-1962-zozimo-12.webp",
    "era": "O bicampeonato do Brasil"
  },
  {
    "id": "brasil-1970-pele-01",
    "name": "Pelé",
    "team": "Brasil 1970",
    "section": "brasil-1970",
    "number": "10",
    "position": "Atacante",
    "rarity": "lendaria",
    "image": "assets/images/stickers/brasil-1970/brasil-1970-pele-01.webp",
    "era": "A seleção eterna"
  },
  {
    "id": "brasil-1970-jairzinho-02",
    "name": "Jairzinho",
    "team": "Brasil 1970",
    "section": "brasil-1970",
    "number": "7",
    "position": "Atacante",
    "rarity": "lendaria",
    "image": "assets/images/stickers/brasil-1970/brasil-1970-jairzinho-02.webp",
    "era": "A seleção eterna"
  },
  {
    "id": "brasil-1970-tostao-03",
    "name": "Tostão",
    "team": "Brasil 1970",
    "section": "brasil-1970",
    "number": "9",
    "position": "Atacante",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-1970/brasil-1970-tostao-03.webp",
    "era": "A seleção eterna"
  },
  {
    "id": "brasil-1970-rivelino-04",
    "name": "Rivelino",
    "team": "Brasil 1970",
    "section": "brasil-1970",
    "number": "11",
    "position": "Meia",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-1970/brasil-1970-rivelino-04.webp",
    "era": "A seleção eterna"
  },
  {
    "id": "brasil-1970-carlos-alberto-05",
    "name": "Carlos Alberto",
    "team": "Brasil 1970",
    "section": "brasil-1970",
    "number": "4",
    "position": "Lateral",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-1970/brasil-1970-carlos-alberto-05.webp",
    "era": "A seleção eterna"
  },
  {
    "id": "brasil-1970-gerson-06",
    "name": "Gérson",
    "team": "Brasil 1970",
    "section": "brasil-1970",
    "number": "8",
    "position": "Meia",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-1970/brasil-1970-gerson-06.webp",
    "era": "A seleção eterna"
  },
  {
    "id": "brasil-1970-clodoaldo-07",
    "name": "Clodoaldo",
    "team": "Brasil 1970",
    "section": "brasil-1970",
    "number": "5",
    "position": "Volante",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-1970/brasil-1970-clodoaldo-07.webp",
    "era": "A seleção eterna"
  },
  {
    "id": "brasil-1970-piazza-08",
    "name": "Piazza",
    "team": "Brasil 1970",
    "section": "brasil-1970",
    "number": "6",
    "position": "Zagueiro",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-1970/brasil-1970-piazza-08.webp",
    "era": "A seleção eterna"
  },
  {
    "id": "brasil-1970-felix-09",
    "name": "Félix",
    "team": "Brasil 1970",
    "section": "brasil-1970",
    "number": "1",
    "position": "Goleiro",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-1970/brasil-1970-felix-09.webp",
    "era": "A seleção eterna"
  },
  {
    "id": "brasil-1970-brito-10",
    "name": "Brito",
    "team": "Brasil 1970",
    "section": "brasil-1970",
    "number": "2",
    "position": "Zagueiro",
    "rarity": "comum",
    "image": "assets/images/stickers/brasil-1970/brasil-1970-brito-10.webp",
    "era": "A seleção eterna"
  },
  {
    "id": "brasil-1970-everaldo-11",
    "name": "Everaldo",
    "team": "Brasil 1970",
    "section": "brasil-1970",
    "number": "3",
    "position": "Lateral",
    "rarity": "comum",
    "image": "assets/images/stickers/brasil-1970/brasil-1970-everaldo-11.webp",
    "era": "A seleção eterna"
  },
  {
    "id": "brasil-1970-paulo-cesar-caju-12",
    "name": "Paulo César Caju",
    "team": "Brasil 1970",
    "section": "brasil-1970",
    "number": "16",
    "position": "Atacante",
    "rarity": "comum",
    "image": "assets/images/stickers/brasil-1970/brasil-1970-paulo-cesar-caju-12.webp",
    "era": "A seleção eterna"
  },
  {
    "id": "brasil-1994-romario-01",
    "name": "Romário",
    "team": "Brasil 1994",
    "section": "brasil-1994",
    "number": "11",
    "position": "Atacante",
    "rarity": "lendaria",
    "image": "assets/images/stickers/brasil-1994/brasil-1994-romario-01.webp",
    "era": "O tetra nos Estados Unidos"
  },
  {
    "id": "brasil-1994-bebeto-02",
    "name": "Bebeto",
    "team": "Brasil 1994",
    "section": "brasil-1994",
    "number": "7",
    "position": "Atacante",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-1994/brasil-1994-bebeto-02.webp",
    "era": "O tetra nos Estados Unidos"
  },
  {
    "id": "brasil-1994-dunga-03",
    "name": "Dunga",
    "team": "Brasil 1994",
    "section": "brasil-1994",
    "number": "8",
    "position": "Volante",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-1994/brasil-1994-dunga-03.webp",
    "era": "O tetra nos Estados Unidos"
  },
  {
    "id": "brasil-1994-taffarel-04",
    "name": "Taffarel",
    "team": "Brasil 1994",
    "section": "brasil-1994",
    "number": "1",
    "position": "Goleiro",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-1994/brasil-1994-taffarel-04.webp",
    "era": "O tetra nos Estados Unidos"
  },
  {
    "id": "brasil-1994-jorginho-05",
    "name": "Jorginho",
    "team": "Brasil 1994",
    "section": "brasil-1994",
    "number": "2",
    "position": "Lateral",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-1994/brasil-1994-jorginho-05.webp",
    "era": "O tetra nos Estados Unidos"
  },
  {
    "id": "brasil-1994-branco-06",
    "name": "Branco",
    "team": "Brasil 1994",
    "section": "brasil-1994",
    "number": "6",
    "position": "Lateral",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-1994/brasil-1994-branco-06.webp",
    "era": "O tetra nos Estados Unidos"
  },
  {
    "id": "brasil-1994-marcio-santos-07",
    "name": "Márcio Santos",
    "team": "Brasil 1994",
    "section": "brasil-1994",
    "number": "15",
    "position": "Zagueiro",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-1994/brasil-1994-marcio-santos-07.webp",
    "era": "O tetra nos Estados Unidos"
  },
  {
    "id": "brasil-1994-aldair-08",
    "name": "Aldair",
    "team": "Brasil 1994",
    "section": "brasil-1994",
    "number": "13",
    "position": "Zagueiro",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-1994/brasil-1994-aldair-08.webp",
    "era": "O tetra nos Estados Unidos"
  },
  {
    "id": "brasil-1994-mauro-silva-09",
    "name": "Mauro Silva",
    "team": "Brasil 1994",
    "section": "brasil-1994",
    "number": "5",
    "position": "Volante",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-1994/brasil-1994-mauro-silva-09.webp",
    "era": "O tetra nos Estados Unidos"
  },
  {
    "id": "brasil-1994-zinho-10",
    "name": "Zinho",
    "team": "Brasil 1994",
    "section": "brasil-1994",
    "number": "9",
    "position": "Meia",
    "rarity": "comum",
    "image": "assets/images/stickers/brasil-1994/brasil-1994-zinho-10.webp",
    "era": "O tetra nos Estados Unidos"
  },
  {
    "id": "brasil-1994-rai-11",
    "name": "Raí",
    "team": "Brasil 1994",
    "section": "brasil-1994",
    "number": "10",
    "position": "Meia",
    "rarity": "comum",
    "image": "assets/images/stickers/brasil-1994/brasil-1994-rai-11.webp",
    "era": "O tetra nos Estados Unidos"
  },
  {
    "id": "brasil-1994-mazinho-12",
    "name": "Mazinho",
    "team": "Brasil 1994",
    "section": "brasil-1994",
    "number": "17",
    "position": "Meia",
    "rarity": "comum",
    "image": "assets/images/stickers/brasil-1994/brasil-1994-mazinho-12.webp",
    "era": "O tetra nos Estados Unidos"
  },
  {
    "id": "brasil-2002-ronaldo-01",
    "name": "Ronaldo",
    "team": "Brasil 2002",
    "section": "brasil-2002",
    "number": "9",
    "position": "Atacante",
    "rarity": "lendaria",
    "image": "assets/images/stickers/brasil-2002/brasil-2002-ronaldo-01.webp",
    "era": "O penta histórico"
  },
  {
    "id": "brasil-2002-ronaldinho-02",
    "name": "Ronaldinho",
    "team": "Brasil 2002",
    "section": "brasil-2002",
    "number": "11",
    "position": "Meia",
    "rarity": "lendaria",
    "image": "assets/images/stickers/brasil-2002/brasil-2002-ronaldinho-02.webp",
    "era": "O penta histórico"
  },
  {
    "id": "brasil-2002-rivaldo-03",
    "name": "Rivaldo",
    "team": "Brasil 2002",
    "section": "brasil-2002",
    "number": "10",
    "position": "Meia",
    "rarity": "lendaria",
    "image": "assets/images/stickers/brasil-2002/brasil-2002-rivaldo-03.webp",
    "era": "O penta histórico"
  },
  {
    "id": "brasil-2002-cafu-04",
    "name": "Cafu",
    "team": "Brasil 2002",
    "section": "brasil-2002",
    "number": "2",
    "position": "Lateral",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-2002/brasil-2002-cafu-04.webp",
    "era": "O penta histórico"
  },
  {
    "id": "brasil-2002-roberto-carlos-05",
    "name": "Roberto Carlos",
    "team": "Brasil 2002",
    "section": "brasil-2002",
    "number": "6",
    "position": "Lateral",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-2002/brasil-2002-roberto-carlos-05.webp",
    "era": "O penta histórico"
  },
  {
    "id": "brasil-2002-marcos-06",
    "name": "Marcos",
    "team": "Brasil 2002",
    "section": "brasil-2002",
    "number": "1",
    "position": "Goleiro",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-2002/brasil-2002-marcos-06.webp",
    "era": "O penta histórico"
  },
  {
    "id": "brasil-2002-kaka-07",
    "name": "Kaká",
    "team": "Brasil 2002",
    "section": "brasil-2002",
    "number": "23",
    "position": "Meia",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-2002/brasil-2002-kaka-07.webp",
    "era": "O penta histórico"
  },
  {
    "id": "brasil-2002-lucio-08",
    "name": "Lúcio",
    "team": "Brasil 2002",
    "section": "brasil-2002",
    "number": "3",
    "position": "Zagueiro",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-2002/brasil-2002-lucio-08.webp",
    "era": "O penta histórico"
  },
  {
    "id": "brasil-2002-edmilson-09",
    "name": "Edmílson",
    "team": "Brasil 2002",
    "section": "brasil-2002",
    "number": "5",
    "position": "Zagueiro",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-2002/brasil-2002-edmilson-09.webp",
    "era": "O penta histórico"
  },
  {
    "id": "brasil-2002-gilberto-silva-10",
    "name": "Gilberto Silva",
    "team": "Brasil 2002",
    "section": "brasil-2002",
    "number": "8",
    "position": "Volante",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-2002/brasil-2002-gilberto-silva-10.webp",
    "era": "O penta histórico"
  },
  {
    "id": "brasil-2002-kleberson-11",
    "name": "Kléberson",
    "team": "Brasil 2002",
    "section": "brasil-2002",
    "number": "15",
    "position": "Meia",
    "rarity": "comum",
    "image": "assets/images/stickers/brasil-2002/brasil-2002-kleberson-11.webp",
    "era": "O penta histórico"
  },
  {
    "id": "brasil-2002-denilson-12",
    "name": "Denílson",
    "team": "Brasil 2002",
    "section": "brasil-2002",
    "number": "17",
    "position": "Atacante",
    "rarity": "comum",
    "image": "assets/images/stickers/brasil-2002/brasil-2002-denilson-12.webp",
    "era": "O penta histórico"
  },
  {
    "id": "brasil-2026-vini-jr-01",
    "name": "Vini Jr",
    "team": "Brasil 2026",
    "section": "brasil-2026",
    "number": "7",
    "position": "Atacante",
    "rarity": "lendaria",
    "image": "assets/images/stickers/brasil-2026/brasil-2026-vini-jr-01.webp",
    "era": "Seleção atual — edição especial"
  },
  {
    "id": "brasil-2026-rodrygo-02",
    "name": "Rodrygo",
    "team": "Brasil 2026",
    "section": "brasil-2026",
    "number": "10",
    "position": "Atacante",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-2026/brasil-2026-rodrygo-02.webp",
    "era": "Seleção atual — edição especial"
  },
  {
    "id": "brasil-2026-neymar-jr-03",
    "name": "Neymar Jr",
    "team": "Brasil 2026",
    "section": "brasil-2026",
    "number": "10",
    "position": "Atacante",
    "rarity": "lendaria",
    "image": "assets/images/stickers/brasil-2026/brasil-2026-neymar-jr-03.webp",
    "era": "Seleção atual — edição especial"
  },
  {
    "id": "brasil-2026-endrick-04",
    "name": "Endrick",
    "team": "Brasil 2026",
    "section": "brasil-2026",
    "number": "9",
    "position": "Atacante",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-2026/brasil-2026-endrick-04.webp",
    "era": "Seleção atual — edição especial"
  },
  {
    "id": "brasil-2026-alisson-05",
    "name": "Alisson",
    "team": "Brasil 2026",
    "section": "brasil-2026",
    "number": "1",
    "position": "Goleiro",
    "rarity": "ouro",
    "image": "assets/images/stickers/brasil-2026/brasil-2026-alisson-05.webp",
    "era": "Seleção atual — edição especial"
  },
  {
    "id": "brasil-2026-bruno-guimaraes-06",
    "name": "Bruno Guimarães",
    "team": "Brasil 2026",
    "section": "brasil-2026",
    "number": "8",
    "position": "Meia",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-2026/brasil-2026-bruno-guimaraes-06.webp",
    "era": "Seleção atual — edição especial"
  },
  {
    "id": "brasil-2026-marquinhos-07",
    "name": "Marquinhos",
    "team": "Brasil 2026",
    "section": "brasil-2026",
    "number": "4",
    "position": "Zagueiro",
    "rarity": "rara",
    "image": "assets/images/stickers/brasil-2026/brasil-2026-marquinhos-07.webp",
    "era": "Seleção atual — edição especial"
  },
  {
    "id": "brasil-2026-raphinha-08",
    "name": "Raphinha",
    "team": "Brasil 2026",
    "section": "brasil-2026",
    "number": "19",
    "position": "Ponta",
    "rarity": "comum",
    "image": "assets/images/stickers/brasil-2026/brasil-2026-raphinha-08.webp",
    "era": "Seleção atual — edição especial"
  },
  {
    "id": "sel-argentina-messi-01",
    "name": "Messi",
    "team": "Argentina",
    "section": "sel-argentina",
    "number": "10",
    "position": "Atacante",
    "rarity": "lendaria",
    "image": "assets/images/stickers/selecoes-2026/sel-argentina-messi-01.webp",
    "era": "Argentina — CONMEBOL"
  },
  {
    "id": "sel-argentina-lautaro-martinez-02",
    "name": "Lautaro Martínez",
    "team": "Argentina",
    "section": "sel-argentina",
    "number": "9",
    "position": "Atacante",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-argentina-lautaro-martinez-02.webp",
    "era": "Argentina — CONMEBOL"
  },
  {
    "id": "sel-argentina-di-maria-03",
    "name": "Di María",
    "team": "Argentina",
    "section": "sel-argentina",
    "number": "11",
    "position": "Meia",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-argentina-di-maria-03.webp",
    "era": "Argentina — CONMEBOL"
  },
  {
    "id": "sel-argentina-emiliano-martinez-04",
    "name": "Emiliano Martínez",
    "team": "Argentina",
    "section": "sel-argentina",
    "number": "1",
    "position": "Goleiro",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-argentina-emiliano-martinez-04.webp",
    "era": "Argentina — CONMEBOL"
  },
  {
    "id": "sel-franca-mbappe-01",
    "name": "Mbappé",
    "team": "França",
    "section": "sel-franca",
    "number": "10",
    "position": "Atacante",
    "rarity": "lendaria",
    "image": "assets/images/stickers/selecoes-2026/sel-franca-mbappe-01.webp",
    "era": "França — UEFA"
  },
  {
    "id": "sel-franca-griezmann-02",
    "name": "Griezmann",
    "team": "França",
    "section": "sel-franca",
    "number": "7",
    "position": "Meia",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-franca-griezmann-02.webp",
    "era": "França — UEFA"
  },
  {
    "id": "sel-franca-tchouameni-03",
    "name": "Tchouaméni",
    "team": "França",
    "section": "sel-franca",
    "number": "8",
    "position": "Volante",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-franca-tchouameni-03.webp",
    "era": "França — UEFA"
  },
  {
    "id": "sel-franca-maignan-04",
    "name": "Maignan",
    "team": "França",
    "section": "sel-franca",
    "number": "1",
    "position": "Goleiro",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-franca-maignan-04.webp",
    "era": "França — UEFA"
  },
  {
    "id": "sel-portugal-cristiano-ronaldo-01",
    "name": "Cristiano Ronaldo",
    "team": "Portugal",
    "section": "sel-portugal",
    "number": "7",
    "position": "Atacante",
    "rarity": "lendaria",
    "image": "assets/images/stickers/selecoes-2026/sel-portugal-cristiano-ronaldo-01.webp",
    "era": "Portugal — UEFA"
  },
  {
    "id": "sel-portugal-bruno-fernandes-02",
    "name": "Bruno Fernandes",
    "team": "Portugal",
    "section": "sel-portugal",
    "number": "8",
    "position": "Meia",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-portugal-bruno-fernandes-02.webp",
    "era": "Portugal — UEFA"
  },
  {
    "id": "sel-portugal-bernardo-silva-03",
    "name": "Bernardo Silva",
    "team": "Portugal",
    "section": "sel-portugal",
    "number": "10",
    "position": "Meia",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-portugal-bernardo-silva-03.webp",
    "era": "Portugal — UEFA"
  },
  {
    "id": "sel-portugal-diogo-costa-04",
    "name": "Diogo Costa",
    "team": "Portugal",
    "section": "sel-portugal",
    "number": "1",
    "position": "Goleiro",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-portugal-diogo-costa-04.webp",
    "era": "Portugal — UEFA"
  },
  {
    "id": "sel-inglaterra-bellingham-01",
    "name": "Bellingham",
    "team": "Inglaterra",
    "section": "sel-inglaterra",
    "number": "10",
    "position": "Meia",
    "rarity": "lendaria",
    "image": "assets/images/stickers/selecoes-2026/sel-inglaterra-bellingham-01.webp",
    "era": "Inglaterra — UEFA"
  },
  {
    "id": "sel-inglaterra-kane-02",
    "name": "Kane",
    "team": "Inglaterra",
    "section": "sel-inglaterra",
    "number": "9",
    "position": "Atacante",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-inglaterra-kane-02.webp",
    "era": "Inglaterra — UEFA"
  },
  {
    "id": "sel-inglaterra-foden-03",
    "name": "Foden",
    "team": "Inglaterra",
    "section": "sel-inglaterra",
    "number": "11",
    "position": "Meia",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-inglaterra-foden-03.webp",
    "era": "Inglaterra — UEFA"
  },
  {
    "id": "sel-inglaterra-saka-04",
    "name": "Saka",
    "team": "Inglaterra",
    "section": "sel-inglaterra",
    "number": "7",
    "position": "Ponta",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-inglaterra-saka-04.webp",
    "era": "Inglaterra — UEFA"
  },
  {
    "id": "sel-espanha-lamine-yamal-01",
    "name": "Lamine Yamal",
    "team": "Espanha",
    "section": "sel-espanha",
    "number": "19",
    "position": "Ponta",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-espanha-lamine-yamal-01.webp",
    "era": "Espanha — UEFA"
  },
  {
    "id": "sel-espanha-pedri-02",
    "name": "Pedri",
    "team": "Espanha",
    "section": "sel-espanha",
    "number": "8",
    "position": "Meia",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-espanha-pedri-02.webp",
    "era": "Espanha — UEFA"
  },
  {
    "id": "sel-espanha-rodri-03",
    "name": "Rodri",
    "team": "Espanha",
    "section": "sel-espanha",
    "number": "16",
    "position": "Volante",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-espanha-rodri-03.webp",
    "era": "Espanha — UEFA"
  },
  {
    "id": "sel-espanha-unai-simon-04",
    "name": "Unai Simón",
    "team": "Espanha",
    "section": "sel-espanha",
    "number": "1",
    "position": "Goleiro",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-espanha-unai-simon-04.webp",
    "era": "Espanha — UEFA"
  },
  {
    "id": "sel-alemanha-musiala-01",
    "name": "Musiala",
    "team": "Alemanha",
    "section": "sel-alemanha",
    "number": "10",
    "position": "Meia",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-alemanha-musiala-01.webp",
    "era": "Alemanha — UEFA"
  },
  {
    "id": "sel-alemanha-wirtz-02",
    "name": "Wirtz",
    "team": "Alemanha",
    "section": "sel-alemanha",
    "number": "17",
    "position": "Meia",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-alemanha-wirtz-02.webp",
    "era": "Alemanha — UEFA"
  },
  {
    "id": "sel-alemanha-havertz-03",
    "name": "Havertz",
    "team": "Alemanha",
    "section": "sel-alemanha",
    "number": "7",
    "position": "Atacante",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-alemanha-havertz-03.webp",
    "era": "Alemanha — UEFA"
  },
  {
    "id": "sel-alemanha-neuer-04",
    "name": "Neuer",
    "team": "Alemanha",
    "section": "sel-alemanha",
    "number": "1",
    "position": "Goleiro",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-alemanha-neuer-04.webp",
    "era": "Alemanha — UEFA"
  },
  {
    "id": "sel-italia-donnarumma-01",
    "name": "Donnarumma",
    "team": "Itália",
    "section": "sel-italia",
    "number": "1",
    "position": "Goleiro",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-italia-donnarumma-01.webp",
    "era": "Itália — UEFA"
  },
  {
    "id": "sel-italia-barella-02",
    "name": "Barella",
    "team": "Itália",
    "section": "sel-italia",
    "number": "18",
    "position": "Meia",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-italia-barella-02.webp",
    "era": "Itália — UEFA"
  },
  {
    "id": "sel-italia-chiesa-03",
    "name": "Chiesa",
    "team": "Itália",
    "section": "sel-italia",
    "number": "14",
    "position": "Ponta",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-italia-chiesa-03.webp",
    "era": "Itália — UEFA"
  },
  {
    "id": "sel-italia-bastoni-04",
    "name": "Bastoni",
    "team": "Itália",
    "section": "sel-italia",
    "number": "23",
    "position": "Zagueiro",
    "rarity": "comum",
    "image": "assets/images/stickers/selecoes-2026/sel-italia-bastoni-04.webp",
    "era": "Itália — UEFA"
  },
  {
    "id": "sel-holanda-van-dijk-01",
    "name": "Van Dijk",
    "team": "Holanda",
    "section": "sel-holanda",
    "number": "4",
    "position": "Zagueiro",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-holanda-van-dijk-01.webp",
    "era": "Holanda — UEFA"
  },
  {
    "id": "sel-holanda-de-jong-02",
    "name": "De Jong",
    "team": "Holanda",
    "section": "sel-holanda",
    "number": "21",
    "position": "Meia",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-holanda-de-jong-02.webp",
    "era": "Holanda — UEFA"
  },
  {
    "id": "sel-holanda-gakpo-03",
    "name": "Gakpo",
    "team": "Holanda",
    "section": "sel-holanda",
    "number": "11",
    "position": "Atacante",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-holanda-gakpo-03.webp",
    "era": "Holanda — UEFA"
  },
  {
    "id": "sel-holanda-depay-04",
    "name": "Depay",
    "team": "Holanda",
    "section": "sel-holanda",
    "number": "10",
    "position": "Atacante",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-holanda-depay-04.webp",
    "era": "Holanda — UEFA"
  },
  {
    "id": "sel-uruguai-valverde-01",
    "name": "Valverde",
    "team": "Uruguai",
    "section": "sel-uruguai",
    "number": "15",
    "position": "Meia",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-uruguai-valverde-01.webp",
    "era": "Uruguai — CONMEBOL"
  },
  {
    "id": "sel-uruguai-darwin-nu-ez-02",
    "name": "Darwin Núñez",
    "team": "Uruguai",
    "section": "sel-uruguai",
    "number": "9",
    "position": "Atacante",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-uruguai-darwin-nu-ez-02.webp",
    "era": "Uruguai — CONMEBOL"
  },
  {
    "id": "sel-uruguai-arrascaeta-03",
    "name": "Arrascaeta",
    "team": "Uruguai",
    "section": "sel-uruguai",
    "number": "10",
    "position": "Meia",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-uruguai-arrascaeta-03.webp",
    "era": "Uruguai — CONMEBOL"
  },
  {
    "id": "sel-uruguai-rochet-04",
    "name": "Rochet",
    "team": "Uruguai",
    "section": "sel-uruguai",
    "number": "1",
    "position": "Goleiro",
    "rarity": "comum",
    "image": "assets/images/stickers/selecoes-2026/sel-uruguai-rochet-04.webp",
    "era": "Uruguai — CONMEBOL"
  },
  {
    "id": "sel-colombia-luis-diaz-01",
    "name": "Luis Díaz",
    "team": "Colômbia",
    "section": "sel-colombia",
    "number": "7",
    "position": "Atacante",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-colombia-luis-diaz-01.webp",
    "era": "Colômbia — CONMEBOL"
  },
  {
    "id": "sel-colombia-james-rodriguez-02",
    "name": "James Rodríguez",
    "team": "Colômbia",
    "section": "sel-colombia",
    "number": "10",
    "position": "Meia",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-colombia-james-rodriguez-02.webp",
    "era": "Colômbia — CONMEBOL"
  },
  {
    "id": "sel-colombia-davinson-sanchez-03",
    "name": "Davinson Sánchez",
    "team": "Colômbia",
    "section": "sel-colombia",
    "number": "23",
    "position": "Zagueiro",
    "rarity": "comum",
    "image": "assets/images/stickers/selecoes-2026/sel-colombia-davinson-sanchez-03.webp",
    "era": "Colômbia — CONMEBOL"
  },
  {
    "id": "sel-colombia-camilo-vargas-04",
    "name": "Camilo Vargas",
    "team": "Colômbia",
    "section": "sel-colombia",
    "number": "12",
    "position": "Goleiro",
    "rarity": "comum",
    "image": "assets/images/stickers/selecoes-2026/sel-colombia-camilo-vargas-04.webp",
    "era": "Colômbia — CONMEBOL"
  },
  {
    "id": "sel-mexico-santiago-gimenez-01",
    "name": "Santiago Giménez",
    "team": "México",
    "section": "sel-mexico",
    "number": "9",
    "position": "Atacante",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-mexico-santiago-gimenez-01.webp",
    "era": "México — CONCACAF"
  },
  {
    "id": "sel-mexico-lozano-02",
    "name": "Lozano",
    "team": "México",
    "section": "sel-mexico",
    "number": "22",
    "position": "Ponta",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-mexico-lozano-02.webp",
    "era": "México — CONCACAF"
  },
  {
    "id": "sel-mexico-edson-alvarez-03",
    "name": "Edson Álvarez",
    "team": "México",
    "section": "sel-mexico",
    "number": "4",
    "position": "Volante",
    "rarity": "comum",
    "image": "assets/images/stickers/selecoes-2026/sel-mexico-edson-alvarez-03.webp",
    "era": "México — CONCACAF"
  },
  {
    "id": "sel-mexico-ochoa-04",
    "name": "Ochoa",
    "team": "México",
    "section": "sel-mexico",
    "number": "13",
    "position": "Goleiro",
    "rarity": "comum",
    "image": "assets/images/stickers/selecoes-2026/sel-mexico-ochoa-04.webp",
    "era": "México — CONCACAF"
  },
  {
    "id": "sel-estados-unidos-pulisic-01",
    "name": "Pulisic",
    "team": "Estados Unidos",
    "section": "sel-estados-unidos",
    "number": "10",
    "position": "Atacante",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-estados-unidos-pulisic-01.webp",
    "era": "Estados Unidos — CONCACAF"
  },
  {
    "id": "sel-estados-unidos-reyna-02",
    "name": "Reyna",
    "team": "Estados Unidos",
    "section": "sel-estados-unidos",
    "number": "7",
    "position": "Meia",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-estados-unidos-reyna-02.webp",
    "era": "Estados Unidos — CONCACAF"
  },
  {
    "id": "sel-estados-unidos-mckennie-03",
    "name": "McKennie",
    "team": "Estados Unidos",
    "section": "sel-estados-unidos",
    "number": "8",
    "position": "Meia",
    "rarity": "comum",
    "image": "assets/images/stickers/selecoes-2026/sel-estados-unidos-mckennie-03.webp",
    "era": "Estados Unidos — CONCACAF"
  },
  {
    "id": "sel-estados-unidos-turner-04",
    "name": "Turner",
    "team": "Estados Unidos",
    "section": "sel-estados-unidos",
    "number": "1",
    "position": "Goleiro",
    "rarity": "comum",
    "image": "assets/images/stickers/selecoes-2026/sel-estados-unidos-turner-04.webp",
    "era": "Estados Unidos — CONCACAF"
  },
  {
    "id": "sel-canada-davies-01",
    "name": "Davies",
    "team": "Canadá",
    "section": "sel-canada",
    "number": "19",
    "position": "Lateral",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-canada-davies-01.webp",
    "era": "Canadá — CONCACAF"
  },
  {
    "id": "sel-canada-david-02",
    "name": "David",
    "team": "Canadá",
    "section": "sel-canada",
    "number": "20",
    "position": "Atacante",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-canada-david-02.webp",
    "era": "Canadá — CONCACAF"
  },
  {
    "id": "sel-canada-larin-03",
    "name": "Larin",
    "team": "Canadá",
    "section": "sel-canada",
    "number": "17",
    "position": "Atacante",
    "rarity": "comum",
    "image": "assets/images/stickers/selecoes-2026/sel-canada-larin-03.webp",
    "era": "Canadá — CONCACAF"
  },
  {
    "id": "sel-canada-crepeau-04",
    "name": "Crépeau",
    "team": "Canadá",
    "section": "sel-canada",
    "number": "16",
    "position": "Goleiro",
    "rarity": "comum",
    "image": "assets/images/stickers/selecoes-2026/sel-canada-crepeau-04.webp",
    "era": "Canadá — CONCACAF"
  },
  {
    "id": "sel-marrocos-hakimi-01",
    "name": "Hakimi",
    "team": "Marrocos",
    "section": "sel-marrocos",
    "number": "2",
    "position": "Lateral",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-marrocos-hakimi-01.webp",
    "era": "Marrocos — CAF"
  },
  {
    "id": "sel-marrocos-ziyech-02",
    "name": "Ziyech",
    "team": "Marrocos",
    "section": "sel-marrocos",
    "number": "7",
    "position": "Meia",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-marrocos-ziyech-02.webp",
    "era": "Marrocos — CAF"
  },
  {
    "id": "sel-marrocos-amrabat-03",
    "name": "Amrabat",
    "team": "Marrocos",
    "section": "sel-marrocos",
    "number": "4",
    "position": "Volante",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-marrocos-amrabat-03.webp",
    "era": "Marrocos — CAF"
  },
  {
    "id": "sel-marrocos-bounou-04",
    "name": "Bounou",
    "team": "Marrocos",
    "section": "sel-marrocos",
    "number": "1",
    "position": "Goleiro",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-marrocos-bounou-04.webp",
    "era": "Marrocos — CAF"
  },
  {
    "id": "sel-japao-kubo-01",
    "name": "Kubo",
    "team": "Japão",
    "section": "sel-japao",
    "number": "20",
    "position": "Meia",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-japao-kubo-01.webp",
    "era": "Japão — AFC"
  },
  {
    "id": "sel-japao-mitoma-02",
    "name": "Mitoma",
    "team": "Japão",
    "section": "sel-japao",
    "number": "7",
    "position": "Ponta",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-japao-mitoma-02.webp",
    "era": "Japão — AFC"
  },
  {
    "id": "sel-japao-endo-03",
    "name": "Endo",
    "team": "Japão",
    "section": "sel-japao",
    "number": "6",
    "position": "Volante",
    "rarity": "comum",
    "image": "assets/images/stickers/selecoes-2026/sel-japao-endo-03.webp",
    "era": "Japão — AFC"
  },
  {
    "id": "sel-japao-suzuki-04",
    "name": "Suzuki",
    "team": "Japão",
    "section": "sel-japao",
    "number": "1",
    "position": "Goleiro",
    "rarity": "comum",
    "image": "assets/images/stickers/selecoes-2026/sel-japao-suzuki-04.webp",
    "era": "Japão — AFC"
  },
  {
    "id": "sel-coreia-do-sul-son-01",
    "name": "Son",
    "team": "Coreia do Sul",
    "section": "sel-coreia-do-sul",
    "number": "7",
    "position": "Atacante",
    "rarity": "ouro",
    "image": "assets/images/stickers/selecoes-2026/sel-coreia-do-sul-son-01.webp",
    "era": "Coreia do Sul — AFC"
  },
  {
    "id": "sel-coreia-do-sul-kim-min-jae-02",
    "name": "Kim Min-jae",
    "team": "Coreia do Sul",
    "section": "sel-coreia-do-sul",
    "number": "4",
    "position": "Zagueiro",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-coreia-do-sul-kim-min-jae-02.webp",
    "era": "Coreia do Sul — AFC"
  },
  {
    "id": "sel-coreia-do-sul-lee-kang-in-03",
    "name": "Lee Kang-in",
    "team": "Coreia do Sul",
    "section": "sel-coreia-do-sul",
    "number": "18",
    "position": "Meia",
    "rarity": "rara",
    "image": "assets/images/stickers/selecoes-2026/sel-coreia-do-sul-lee-kang-in-03.webp",
    "era": "Coreia do Sul — AFC"
  },
  {
    "id": "sel-coreia-do-sul-cho-04",
    "name": "Cho",
    "team": "Coreia do Sul",
    "section": "sel-coreia-do-sul",
    "number": "9",
    "position": "Atacante",
    "rarity": "comum",
    "image": "assets/images/stickers/selecoes-2026/sel-coreia-do-sul-cho-04.webp",
    "era": "Coreia do Sul — AFC"
  }
];
